spring.application.name=grameone_backend
server.port=${PORT:8080}

# PostgreSQL Datasource (Supabase Pooler)
spring.datasource.url=jdbc:postgresql://aws-0-eu-central-1.pooler.supabase.com:5432/postgres
spring.datasource.username=postgres.ifomzjccrqkikdicyvhy
spring.datasource.password=grameOne2026
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# API documentation paths
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui/index.html


# Cloudflare R2 Configuration (S3 Compatible API)
cloudflare.r2.access-key=af0a1fae23344273d442d822153603db
cloudflare.r2.secret-key=3ad80fb48004210cf7972c5683067deb38f492dc31a33f35c4dd4e29ab008b6b
cloudflare.r2.region=auto
cloudflare.r2.bucket-name=grameone
cloudflare.r2.endpoint=https://4ce23afb1e23344b92945a2dbde9fc00.r2.cloudflarestorage.com

# JWT Configuration
jwt.secret=9a2f8c7d6e5b4a3f2e1d0c9b8a7f6e5d4c3b2a1f0e9d8c7b6a5f4e3d2c1b0a9f8e7d6c5b4a3f2e1d0c9b8a7f6e5d4c3b2a1f0e9d8c7b6a5f4e3d2c1b0a9f
jwt.expiration=86400000

# File Upload Limit
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB
